[profile.default]
src = 'src'
test = 'test/'
out = 'out'
libs = ['lib']
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 1_000
via-ir = true
ffi = true
evm_version = "cancun"

[fmt]
line_length = 80
number_underscore = "thousands"

[rpc_endpoints]
optimism = "${OPTIMISM_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }