name: coverage

on: [push]

env:
    FOUNDRY_PROFILE: default

jobs:
    check:
        strategy:
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Report Coverage
              run: |
                forge coverage --fork-url ${{ secrets.ARBITRUM_RPC_URL }} --report lcov --via-ir --optimizer-runs 200 --optimize

            - name: Upload Coverage Report
              uses: codecov/codecov-action@v3
              with:
                  files: ./lcov.info
                  name: codecov-unit
                  fail_ci_if_error: true
                  verbose: true
